services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Event\:
        resource: '../../src/Event/*'

    App\Event\Subscriber\PlacesBlockSubscriber:
        arguments:
            $queryType: '@App\QueryType\BlockQueryType'
            $tagHandler: '@ezplatform.http_cache.fos_tag_handler.xkey'

    App\Event\Subscriber\TastesBlockSubscriber:
        arguments:
            $queryType: '@App\QueryType\BlockQueryType'
            $tagHandler: '@ezplatform.http_cache.fos_tag_handler.xkey'

    App\Event\TemplateAttributeBlockNameListener:
        tags:
            - { name: kernel.event_subscriber }

    App\Event\PageFieldType\Attribute\AttributeSerializationSubscriber: ~

#    App\Event\Listener\RenderMenuListener:
#        arguments:
#            $personalizationCustomerId: '%ez_recommendation.default.yoochoose.customer_id%'
#            $personalizationLicenseKey: '%ez_recommendation.default.yoochoose.license_key%'
#        tags:
#            - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: renderMenu, priority: -45 }
