services:
    App\Installer\PlatformEEDemoInstaller:
        autowire: true
        parent: EzSystems\PlatformInstallerBundle\Installer\CoreInstaller
        class: App\Installer\PlatformEEDemoInstaller
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
        tags:
            - { name: ezplatform.installer, type: ezplatform-ee-demo }

#    App\Installer\PlatformEEDemoTestLayoutsInstaller:
#        autowire: true
#        autoconfigure: false
#        parent: EzSystems\PlatformInstallerBundle\Installer\DbBasedInstaller
#        calls:
#            - [setEnvironment, ["%kernel.environment%"]]
#        tags:
#            - { name: ezplatform.installer, type: demo-test-layouts }
