services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        App\Menu\MenuProviderInterface:
            tags: ['menu_provider_supported_strategy']

    App\Menu\:
        resource: '../../src/Menu/*'

    App\Menu\MenuProviderStrategy:
        arguments:
            $providers: !tagged_iterator 'menu_provider_supported_strategy'

    App\Menu\CacheAware\MenuGenerator: ~

    App\Menu\MenuBuilder:
        arguments:
            $menuIncludedItems: '%app.menu%'
        tags:
            - { name: knp_menu.menu_builder, method: createMaisonMainMenu, alias: maison_main }
            - { name: knp_menu.menu_builder, method: createMaisonHeaderMenu, alias: maison_top }
            - { name: knp_menu.menu_builder, method: createMaisonFooterMenu, alias: maison_footer }
            - { name: knp_menu.menu_builder, method: createProfessionalsMainMenu, alias: professionals_main }
