services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\QueryType\:
        resource: '../../src/QueryType/*'

    App\QueryType\MenuQueryType:
        arguments:
            $languages: '%languages%'

    App\QueryType\ChildrenQueryType:
        tags:
            - {name: ezpublish.query_type}
