services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Search\QueryExecutor\LocationSearchQueryExecutor: ~

    App\Search\QueryExecutorInterface: '@App\Search\QueryExecutor\LocationSearchQueryExecutor'

    App\Search\PagerSearchContentMapper: ~
