ezplatform_page_fieldtype:
    layouts:
        1w__2_1__1:
            identifier: '1w__2_1__1'
            name: 'Mixed columns, 4 Zones'
            description: 'Mixed columns, 4 Zones'
            thumbnail: '/bundles/ezplatformpagefieldtype/images/layouts/default.png'
            template: '@ezdesign/layouts/1w__2_1__1.html.twig'
            zones:
                top:
                    name: 'Top wide zone'
                middle_left:
                    name: 'Middle left zone'
                middle_right:
                    name: 'Middle right zone'
                bottom:
                    name: 'Bottom zone'

#    blocks:
#        contentList:
