ezplatform_page_fieldtype:
    blocks:
        hero:
            name: Hero
            category: default
            thumbnail: '/assets/images/page_builder/blocks/hero.svg#hero'
            configuration_template: '@EzPlatformPageBuilder/page_builder/block/config/embed.html.twig'
            attributes:
                text:
                    name: Text
                    type: text
                    validators:
                        not_blank:
                            message: You must provide a text
                        regexp:
                            options:
                                pattern: '/[^\\s]/'
                            message: Only valid HTML code is allowed
                contentId:
                    name: Image
                    type: embed
                    validators:
                        not_blank:
                            message: You must provide value
                        regexp:
                            options:
                                pattern: '/[0-9]+/'
                            message: Choose a Content item

        places:
            name: Places
            category: default
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#places'
            attributes:
                contentId:
                    name: Places
                    type: embed
                    validators:
                        not_blank:
                            message: You must provide value
                        regexp:
                            options:
                                pattern: '/[0-9]+/'
                            message: Choose a folder with Content items of the type Places

        tastes:
            name: Tastes
            category: default
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#file'
            attributes:
                contentId:
                    type: 'embed'
                    name: Parent
                    validators:
                        not_blank:
                            message: You must provide value
                        regexp:
                            options:
                                pattern: '/[0-9]+/'
                            message: Choose a Content item
                limit:
                    type: 'integer'
                    name: Limit
                    validators:
                        not_blank:
                            message: You must provide value
                        regexp:
                            options:
                                pattern: '/^[1-9][0-9]*$/'
                            message: Limit must be a number greater than 0

        video:
            attributes:
                controls:
                    name: Display controls
                    type: radio
                    validators:
                        not_blank:
                            message: Controls must be set
                        regexp:
                            options:
                                pattern: '/^(1|0){1}/'
                            message: Display controls
                    value: 0
                    options:
                        multiple: false
                        choices:
                            'No': 0
                            'Yes': 1
                            
                autoplay:
                    name: Auto play
                    type: radio
                    validators:
                        not_blank:
                            message: Auto play must be set
                        regexp:
                            options:
                                pattern: '/^(1|0){1}/'
                            message: Auto play
                    value: 0
                    options:
                        multiple: false
                        choices:
                            'No': 0
                            'Yes': 1

                loop:
                    name: Loop
                    type: radio
                    validators:
                        not_blank:
                            message: Loop must be set
                        regexp:
                            options:
                                pattern: '/^(1|0){1}/'
                            message: Loop
                    value: 0
                    options:
                        multiple: false
                        choices:
                            'No': 0
                            'Yes': 1

                width:
                    type: 'integer'
                    name: Width
                    validators:
                        not_blank:
                            message: You must provide width value
                        regexp:
                            options:
                                pattern: '/^[1-9][0-9]*$/'
                            message: Width must be a number greater than 0

                height:
                    type: 'integer'
                    name: Height
                    validators:
                        not_blank:
                            message: You must provide height value
                        regexp:
                            options:
                                pattern: '/^[1-9][0-9]*$/'
                            message: Height must be a number greater than 0

        contentlist:
            configuration_template: '@EzPlatformPageBuilder/page_builder/block/config/content_list.html.twig'
            thumbnail: '/bundles/ezplatformadminui/img/ez-icons.svg#contentlist'
