app.contact.submitted:
    path: /contact/submitted
    defaults:
        _controller: App\Controller\ContactFormController::submittedAction
        template: "@ezdesign/full/contact_form_submitted.html.twig"
    methods: [GET]
